### ISSUE TITLE
Blank Cells not appearing in one sheet in spreadsheet

### ISSUE THREAD

**Issue by KeithHanson** [pythonicrubyist/creek#10]
I have no clue what is causing this, but I have narrowed the problem down to one sheet in this file:

http://static.crunchbase.com/exports/crunchbase_monthly_export.xlsx

When looking at all other sheets except for sheet 4 (Investments), nils are returned for blank cells. 

I just spent several hours scratching my head trying to figure out a gem that would work, and Dullard is so far the fastest option. When I dug in, I noticed other issues referencing this and assumed it wasn't fixed. 

In my testing, though, I'd only tested with the same sheet. In testing every other sheet, there is no problem. 

Is anyone else seeing the same thing? Any advice? 

I'll be able to get at the data I want from other sheets, but would love to help track this one down if I can. Let me know if there's any more info you need from me!

**Comment by pythonicrubyist** [comment]
The problem seems to be that the XML behind the sheet is not formatted properly.
