### ISSUE TITLE
No such file or directory @ rb_sysopen - /tmp/open-uri20220126-8-xdogjo

### ISSUE THREAD

**Issue by leom806** [pythonicrubyist/creek#102]
Hey guys.

I was getting this error here when trying to read a XLSX spreadsheet remotely with 5k+ rows.

`No such file or directory @ rb_sysopen - /tmp/open-uri20220126-8-xdogjo` - Example error message

I'm not sure how that happens but I could fix it here by using your `Creek::Book#download_file` method like this:

![image](https://user-images.githubusercontent.com/7718776/151098898-363e9e16-97a8-41a5-baf1-9e51f7d75d00.png)

I'm basically downloading the file locally but what really did the change was to not call the `path` method in the `Tempfile.new` without an instance variable.

Looks like some Garbage Collection issue, not sure.

I thought that would help. 
Thanks for your great work.

**Comment by stiig** [comment]
@leom806 I had the same issue, try to unlink file after processing, for more details - https://www.hilman.io/blog/2016/01/tempfile/
