### ISSUE TITLE
Documentation Not Loading

### ISSUE THREAD

**Issue by evilthreads669966** [pythonicrubyist/creek#110]
I've been trying to look at the creek API documentation on rubygems.org all day. Is this a new issue or has this been going on for awhile? I don't know if you have the documentation available for download anywhere.

**Comment by pythonicrubyist** [comment]
@evilthreads669966 the gem is published here: https://rubygems.org/gems/creek Can you please elaborate a little more on where you are expecting the API to be documented? I do not understand your question.

**Comment by evilthreads669966** [comment]
https://rubydoc.info/gems/creek is what is not loading.
