### ISSUE TITLE
Array sorting exception by certain type of xlsx

### ISSUE THREAD

**Issue by martinsabo** [pythonicrubyist/creek#12]
Hi,
i have recently stumbled upon your handy library. Unfortunately it was not working out of box for my xlsx files. Sorting exception was thrown.

```
ArgumentError:
       comparison of NilClass with String failed
     # ./lib/creek/sheet.rb:101:in `sort'
```
It looks that my files are somehow "malformed" and the Nokogiri XML reader parses our weird node with no content which is stored as  nil => "" pair in cells hash. The nil key value blows the array sorting. And should be not there in general. The problem disappears after i re-save the file in LibreOffice.

There is a simple fix for my scenario together with example spec and malformed fixture file in my fork:
https://github.com/martinsabo/creek/commit/5a6a3383a498aee267c390e430bf8507202d2046

The weird node is parsed out from this part:
```
<?xml version="1.0" encoding="UTF-8"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><dimension ref="A1"/><sheetViews><sheetView workbookViewId="0" tabSelected="true"/></sheetViews><sheetFormatPr defaultRowHeight="15.0" baseColWidth="40"/><cols><col min="1" max="1" width="60.0" customWidth="true"/><col min="2" max="2" width="20.0" customWidth="true"/></cols>
```
If somebody had similar problem please post a comment.

Thank you.

**Comment by jthibeaux** [comment]
Ran across a similar problem, but in trying @martinsabo 's fix, it still did not accurately represent the rows (even though the exception stopped firing).  I ended up with some cells with garbage and others repeating the same data.

**Comment by jthibeaux** [comment]
Was able to work around by saving it as Excel 2004 XML and then back to xlsx -- it is meant to be just straight data, so this workaround will do me.

**Comment by pythonicrubyist** [comment]
It would be difficult to handle malformed XML files behind Excel sheets.
