### ISSUE TITLE
excel_col_names bloats memory

### ISSUE THREAD

**Issue by subelsky** [pythonicrubyist/creek#15]
While profiling some of our application code, I noticed that these lines:

https://github.com/pythonicrubyist/creek/blob/4808520c53b1372161ad85f4e7612b7bf722f7b4/lib/creek/sheet.rb#L28-L30

cause 16384 objects (about 1.5MB) to be permanently allocated, since the class variable can't be garbage collected.

I have some ideas for how to fix, if you are up for it:

1) Make it a instance variable, so the whole object can be garbage collected when the `Book` goes out of scope. The code is already fast, and is already re-generating this hash every time a `Book` gets initialized, so it should not be noticeable.

2) Make `@ excel_col_names` a sparse hash, so only the subset of column names that are needed for a particular spreadsheet are used, something like:
```ruby
excel_col_names = Hash.new do |key,hash|
  hash[col_name(key)] = key  # I think this is not quite right, but you get the idea
end
```
...so then you could reference any of the 16384 column names lazily at any point in the code

I'm totally up for making these changes if you're game

**Comment by cec** [comment]
Hi @subelsky, did you get any update from @pythonicrubyist? 
If there's no reply since May, I think this gem is dead...

**Comment by subelsky** [comment]
@cec no reply, I forgot about this. I think No. 1 is still pretty viable, we should just fork and submit a pull request

**Comment by cec** [comment]
I'm not sure if it is worth the effort though: I asked you if there was any reply because I am looking for a  solid gem to work with Excel files for data import. 

While waiting for your reply I found this [roo](https://github.com/roo-rb/roo) fork which is active and has way more community around it (just look at the stars...).

**Comment by subelsky** [comment]
in our experience creek is still much better/faster for `.xlsx` processing  -- but if you have to use old-style `.xls` as well as other spreadsheet formats, that fork is good too. We use both.

**Comment by cec** [comment]
That's valuable information, thanks for sharing it!
At the moment I am still not sure about which file type I have to work with as it depends on what the people in the other organizations will be sending me.

**Comment by thirtyseven** [comment]
@subelsky My gem [dullard](/thirtyseven/dullard) is still somewhat maintained and accepting pull requests.   Lots of bugs have been fixed from the initial versions.

**Comment by subelsky** [comment]
@thirtyseven thanks! I think I looked at both and can't quite remember why we picked `creek` -- good to know there are alternatives. We see such a wide variety of XLSX data I wouldn't be surprised if we end up using all 3 gems :-)

cc @kbladow

**Comment by pythonicrubyist** [comment]
I am looking into the issue and will resolve it in the next day or two.

**Comment by pythonicrubyist** [comment]
@subelsky Thanks for your suggestions and sorry for the delay in my response.

I'm going with your first suggestion to fix the problem. I will make the code changes and publish a new gem version.

If you have any futhur thoughts on this, please let me know.

**Comment by pythonicrubyist** [comment]
@subelsky and @kbladow

I have published creek (1.0.9) with the fix based on @subelsky 's suggestion. I hope this helps.

**Comment by pythonicrubyist** [comment]
@subelsky and @kbladow

Hopefully version 1.0.9 has resolved the issue. I am going to close this issue for now.

In case you have nay further comments, pleas feel free to reopen the issue.

**Comment by subelsky** [comment]
Thanks @pythonicrubyist ! This will help us stay lean n mean. /cc @kbladow
