### ISSUE TITLE
Make typecasting optional

### ISSUE THREAD

**Issue by why-el** [pythonicrubyist/creek#18]
This is an excellent and fast gem, but I was surprised to see that it does casting to various Ruby types. Perhaps we can make that optional?

**Comment by pythonicrubyist** [comment]
@why-el What is the alternative? Returning Nokogiri XML objects? That would be harder to deal with than Ruby objects.
Please let me know if you have a better idea.

**Comment by mattnedrich** [comment]
I assume there would be interest in reading all values as strings, instead of auto casting them to other types (e.g., numbers, dates, etc.).
