### ISSUE TITLE
Open file through URI

### ISSUE THREAD

**Issue by shuchigupta** [pythonicrubyist/creek#22]
Hi,

I have a requirement where-in I need to store my excel files in S3. Is it possible for creek to read files directly using S3 URI?

Thanks,
Shuchi

**Comment by pythonicrubyist** [comment]
Unfortunately this is not supported by Creek. Pull  Requests are welcome though :)

**Comment by garyfoster** [comment]
Is there a pull request or fork that solves this yet?
