### ISSUE TITLE
Creek rounding numbers

### ISSUE THREAD

**Issue by tostasqb** [pythonicrubyist/creek#23]
I have a cell with the value 2.16 that is formatted as as number with no decimal places. Creek reads 2. 
![image](http://s12.postimg.org/qir9nwf7x/Screen_Shot_2016_01_18_at_13_10_45.png)

**Comment by pythonicrubyist** [comment]
@tostasqb The whole process of parsing of numbers is being redone in the next version of creek(2.0) which will be released soon. That should solve this issue.

**Comment by iwan** [comment]
Hi, I found the same problem in the current version (2.4.1).
Any idea?

**Comment by pythonicrubyist** [comment]
@iwan can you share a sample file with has this issue?

**Comment by iwan** [comment]
```ruby
require 'creek'
creek = Creek::Book.new './book_1.xlsx'
sheet = creek.sheets[0]
sheet.rows.each.with_index do |row, i|
    puts row # => {"A1"=>"Content 1", "B1"=>nil, "C1"=>nil, "D1"=>"Content 3"}
end
``` 

[book_1.xlsx](https://github.com/pythonicrubyist/creek/files/2257715/book_1.xlsx)

Result:
```
{"A1"=>"1.234", "B1"=>1.234, "C1"=>1.234, "D1"=>1}
{"A2"=>"2.468", "B2"=>2.468, "C2"=>2.468, "D2"=>2}
{"A3"=>"3.702", "B3"=>3.702, "C3"=>3.702, "D3"=>3}
{"A4"=>"1", "B4"=>"2", "C4"=>"3", "D4"=>"4"}
```
Another strange behaviour is that some numbers are recognized as strings and other not.
