### ISSUE TITLE
How to parse date?

### ISSUE THREAD

**Issue by nikitasingh** [pythonicrubyist/creek#25]
I am trying to import date from an excelsheet, its in the format of dd/mm/yyyy or dd-mm-yyyy.
The cell type is date. When parsing the sheet, it converts that to a number and eventually wrong date.
I was not able to find how to save correct date using the gem. Could you please help?

**Comment by kamilhism** [comment]
@nikitasingh, check out [this PR](https://github.com/pythonicrubyist/creek/pull/27), it should fix some issues with wrong dates

**Comment by pythonicrubyist** [comment]
@nikitasingh Version 1.1.2 has been released with bug fixes for dates. If you are still facing an issue, please reopen the issue, share the Excel file and the details of the problem.
