### ISSUE TITLE
Access Remote Url file

### ISSUE THREAD

**Issue by sawantprasann** [pythonicrubyist/creek#28]
how to access remote url file. when i try Creek::Book.new "https://whateverurl.xlsx" then its show error 
File https://whateverurl.xlsx not found. any idea how to solve this error.

**Comment by pythonicrubyist** [comment]
@sawantprasann remote parsing is not supported at this point. I can add it to the backlog for a future release.

**Comment by lacostenycoder** [comment]
This doesn't seem to work just following docs in readme.
Tested on MacOS, ruby version: ruby 2.6.2p47
creek version: creek (2.4.4)

```
remote_url = 'http://dev-builds.libreoffice.org/tmp/test.xlsx'
Creek::Book.new remote_url, remote: true
=>Zip::Error: Zip end of central directory signature not found
```
