### ISSUE TITLE
Handle weird character escape sequence

### ISSUE THREAD

**Issue by jarredholman** [pythonicrubyist/creek#29]
The OOXML spec allows non-printable characters to be encoded using an escape sequence `_xHHHH_` where `HHHH` is the hex code of the character.

I have received a few xlsx files that contain `_x000D_` sequences (the carriage return character).

If you load the file in creek (or open the xml file in a text editor), the cell contents will be
`"first line_x000D_\nsecond line"`
Where `_x000D_` is the carriage return character, and the line feed character is encoded normally.

When you open it in excel you just see a newline.

see:
- https://github.com/roo-rb/roo/issues/223
- https://github.com/hadley/readxl/issues/51

**Comment by pythonicrubyist** [comment]
@jarredholman , I have included your PR in the next major release of the gem. Thanks for your contribution.

**Comment by jarredholman** [comment]
Was there a reason this fix was reverted?
