### ISSUE TITLE
Creek reads first row as empty [] even though it has data

### ISSUE THREAD

**Issue by premkumarmani** [pythonicrubyist/creek#37]
When running creek on mac, i see this issue of returning first row as empty [].  Once I open the file in Microsoft Excel for mac, and save it, then it reads fine.
Am I missing any thing?  Any help/suggestions would be great.  
Ruby 2.3.0
creek 1.1.2
MacOS Sierra 10.12.3

**Comment by chifung7** [comment]
I also had this problem.  My workaround is set `book.use_shared_strings = true` before `#serialize`.

**Comment by thekendalmiller** [comment]
I am also having this issue. `book.use_shared_strings = true` doesn't appear to be an option in the latest version of creek but I'm not sure it's related.

In my case, if I look at the sheet xml, I can see the "empty" sheet is using `t="inlineStr"` for cell types and creek does not read this.
If I open and save the file, sheet xml is now using `t="s"` and creek reads the sheet fine.

**Comment by thekendalmiller** [comment]
I am also on `1.1.2` of creek. Looks like there was a pull request to fix it but it's not in master yet? https://github.com/pythonicrubyist/creek/pull/31

**Comment by chifung7** [comment]
Oh sorry I mixed it up with a similar issue from `axlsx gem`.  Please ignore my comment

**Comment by SGrondin** [comment]
@premkumarmani @thekendalmiller 
This should be fixed in my fork at https://github.com/partpilotllc/creek
Just add this line to your Gemfile:
```ruby
gem 'creek', '2.0.0-partpilot', :git => "https://github.com/PartPilotLLC/creek.git", :tag => "v2.0.0-partpilot"
```
There's also a PR for it (https://github.com/pythonicrubyist/creek/pull/47), but I have no idea when/if it'll be merged.

**Comment by thekendalmiller** [comment]
Thanks @SGrondin - I'll give it a try. I looked over the pull request and it looks good, but I don't see anything obvious that would fix the inlineStr issue. There is an unmerged PR for it here: https://github.com/pythonicrubyist/creek/pull/31

**Comment by thekendalmiller** [comment]
The partpilot branch does not fix the inlineStr issue.

**Comment by pythonicrubyist** [comment]
PR #47 has been merged to master and should solve this issue.

**Comment by SGrondin** [comment]
@thekendalmiller Make sure you use `2.0.1-partpilot` or, even better, the new Creek 2.0

**Comment by thekendalmiller** [comment]
@SGrondin Thanks for the comment! The latest creek (or your branch) fixes the inlineStr issue.

This commit https://github.com/pythonicrubyist/creek/commit/de44c4504f7e4bba353874d98b2b167daa419673
