### ISSUE TITLE
How to close the file after parsing through the xlsx file 

### ISSUE THREAD

**Issue by pentanareshkumar** [pythonicrubyist/creek#45]
Hi,

I am using creek gem in my project, as bellow shown code. After parsing through the xlsx file, how do i close the file ( in below code how do i close the parseFile). Do we have something like "parseFile.close"
require 'creek'
parseFile= Creek::Book.new 'specs/fixtures/sample.xlsx'
sheet= parseFile.sheets[0]

With Regards,
Naresh

**Comment by SGrondin** [comment]
Just do
```ruby
parseFile.close
```
