### ISSUE TITLE
Is it possible to disable the sheet type conversion?

### ISSUE THREAD

**Issue by phillycheeze** [pythonicrubyist/creek#49]
If I upload an excel workbook where a column is labeled as a "Number" type, Creek automatically calls `.to_f` on the value. I want to only get the string value of the original cell. 

Is this possible? Kind of deal break since some users upload workbooks that have the Number/Decimal type set on a column, and then I get weird values like "5.109182736E9" when I want to interpret it as a literal string (the original being "5109182736")

Thanks!

**Comment by phillycheeze** [comment]
Should also mention that calling `.to_s` doesn't quite work since it will give me back a string with ".0" at the end.

**Comment by anetrusov** [comment]
+1 on this issue
I love creek because of its simplicity and fast speed, would be great to define column types manually

**Comment by pythonicrubyist** [comment]
@phillycheeze and @anetrusov , the fast speed of creek comes at the cost of not having automatic type detection for each cell value.

I remember when I wrote the first draft of this gem, there was a huge performance difference in having object type detection or not, so I decided to go with the assumption that all cells in a column are of the same type.

**Comment by anetrusov** [comment]
@pythonicrubyist 

thanks for the reply, didn't see it earlier. we've fixed it by monkey patching:
```ruby
module Extensions
  module Creek
    module Converter
      def call(value, type, style, options = {})
        return nil if value.blank?

        if type == 'n' && !::Creek::Styles::Converter::DATE_TYPES.include?(style)
          return convert_number(value)
        end

        super
      end

      def convert_number(value)
        Integer(value)
      rescue
        value.to_f
      end
    end
  end
end

Creek::Styles::Converter.singleton_class.prepend(Extensions::Creek::Converter)
```

still works great. thanks for your contribution to opensource.

**Comment by pythonicrubyist** [comment]
👍
