### ISSUE TITLE
Not reading data. At all.

### ISSUE THREAD

**Issue by myfitment** [pythonicrubyist/creek#55]
I have an Excel file, created with Axlsx, that Excel opens just fine.
There is only one sheet.
When looping through the rows of that sheet, the values look like this:

    Row 1: {}
    Row 2: {"A2"=>nil, "B2"=>nil, "C2"=>nil, "D2"=>nil, "E2"=>nil, "F2"=>1.0, "G2"=>20.0, "H2"=>179.0, "I2"=>nil, "J2"=>nil, "K2"=>nil, "L2"=>nil, "M2"=>nil, "N2"=>1.0, "O2"=>55.0, "P2"=>nil, "Q2"=>nil, "R2"=>nil, "S2"=>nil, "T2"=>nil, "U2"=>nil, "V2"=>nil, "W2"=>55.0, "X2"=>nil, "Y2"=>nil, "Z2"=>13.0, "AA2"=>8.0, "AB2"=>13.0, "AC2"=>nil, "AD2"=>8668.0, "AE2"=>nil, "AF2"=>63692.0, "AG2"=>nil, "AH2"=>229.0, "AI2"=>nil, "AJ2"=>33990.0, "AK2"=>nil, "AL2"=>0.0, "AM2"=>nil, "AN2"=>nil, "AO2"=>nil, "AP2"=>0.0, "AQ2"=>0.0, "AR2"=>0.0, "AS2"=>nil, "AT2"=>nil, "AU2"=>0.0, "AV2"=>nil, "AW2"=>nil, "AX2"=>nil, "AY2"=>0.0, "AZ2"=>0.0, "BA2"=>0.0, "BB2"=>0.0, "BC2"=>nil, "BD2"=>nil, "BE2"=>nil}

The first row is completely blank! In reality it has headers going out to column BD.

If I cut and paste the contents into a brand new sheet, and save it, the file is read properly.

And yet, Excel can read either file.

Any idea what's going on here?

**Comment by pythonicrubyist** [comment]
Please refer to this issue:

https://github.com/pythonicrubyist/creek/issues/37
