### ISSUE TITLE
Is it possible to know the amount of rows before hand ?

### ISSUE THREAD

**Issue by tommyalvarez** [pythonicrubyist/creek#62]
Something like `sheet.rows.size`. Didn't find anything in the documentation, not even browsing the source code

**Comment by SGrondin** [comment]
Did you even look at what `sheet.rows` returns? It's an Enumerable, so just do `sheet.rows.count`.....

**Comment by tommyalvarez** [comment]
@SGrondin I did, i even look at what sheet.rows.methods returned to inspect the available methods and did not peek count, maybe by distraction. I do not remember all of the core classes methods by hard, specially of Enumerable. I was just asking a question, there was no need to answer it in that terms. Thanks anyway for your help

**Comment by SGrondin** [comment]
Sorry, I didn't mean to come across as rude. I'm glad it answered your question 😅
