### ISSUE TITLE
Replace HTTParty with http.rb?

### ISSUE THREAD

**Issue by bgentry** [pythonicrubyist/creek#63]
Would you be opposed to replacing this gem's use of HTTParty with another HTTP lib, like [http.rb](https://github.com/httprb/http)? It appears it is only used in [one place](https://github.com/pythonicrubyist/creek/blob/04a8df26e0dc957264ce6b36a1da0597b201d394/lib/creek/book.rb#L26).

HTTParty's post-install message is a nuisance that I always try to keep out of my dependency tree:

> When you HTTParty, you must party hard!

As a bonus, http.rb should be faster too. I'd be happy to send a PR.

**Comment by bgentry** [comment]
Here's one of many issues where users have begged the maintainer to remove that obnoxious post-install message and have been ignored: https://github.com/jnunemaker/httparty/pull/321

**Comment by pythonicrubyist** [comment]
@bgentry I totally agree.

**Comment by pythonicrubyist** [comment]
fixed by @bgentry 's contribution at https://github.com/pythonicrubyist/creek/pull/64 .
