### ISSUE TITLE
xml-namespaces in a book

### ISSUE THREAD

**Issue by st0ck** [pythonicrubyist/creek#67]
I've met an xlsx file with xml-prefixes in a workbook and worksheets. Currently parsing such file returns zero sheets :(
I don't know what application saves xlsx files that way and unfortunately I can't share the file - it contains confidential information. I fixed an issue in this PR (https://github.com/pythonicrubyist/creek/pull/66). 
Sorry for lots of changes, I just tried to reduce code duplication.

**Comment by pythonicrubyist** [comment]
merged PR (#66).
