### ISSUE TITLE
Open xlsx with known Password for reading

### ISSUE THREAD

**Issue by pcoughlin** [pythonicrubyist/creek#69]
I am looking for a way to open a password protected file in Rails. We know the password, so this is not cracking, just opening like normal but with the use of the password.
The client wants to upload a password protected file (details have potential private data in it).
We need to open the file and process the contents.
Normal ... just with the twist of using the password to open the file.

I searched you issues for 'password' and 'protected' and did not see anything. Also it does not appear to be in the docs.

Thanks!

**Comment by pythonicrubyist** [comment]
Added to the backlog for 3.0 release.
