### ISSUE TITLE
Large numbers casted as BigDecimal

### ISSUE THREAD

**Issue by phildionne** [pythonicrubyist/creek#70]
Not sure if it's intended but a original value of `783294732` becomes `7.83294732E8`. I dug and it seems to be a conversion happening to large numbers, which are casted as BigDecimal.

Why then the resulting value is a stringified BigDecimal, and not a BigDecimal instance ?

**Comment by pythonicrubyist** [comment]
fixed. But it your column's format is set to "string", you will get the string representation. There is nothing I can do about that.
