### ISSUE TITLE
Text read from excel files is html escaped

### ISSUE THREAD

**Issue by davich** [pythonicrubyist/creek#74]
I have an xlsx file with an ampersand in it (`&`) and when I read the file using Creek, it becomes `&amp;`. Is this kind of html escaping expected? Is there a way of turning it off? Thanks

**Comment by davich** [comment]
[testfile.xlsx](https://github.com/pythonicrubyist/creek/files/2631187/testfile.xlsx)

```
book = Creek::Book.new file_path
book.sheets[0].rows.each do |row|
    p row.values
end
```

**Comment by Rajagopalan-M** [comment]
@davich 

Hi, I have given the value a&b in a cell and I can read as it is. I am not facing this problem. Can you check it now?

**Comment by davich** [comment]
Have you tried it with the file I attached? Is there some formatting on that cell that makes it read differently?

**Comment by Rajagopalan-M** [comment]
yes, I tried I perfectly reads, this is the code I have written

> 
> require 'creek'
> @SanityWorkBook = Creek::Book.new "testfile.xlsx"
> @sheet = @SanityWorkBook.sheets.detect {|sheet, index| sheet.name.eql? "Inspirations"}
> @header, *@dataSets = @sheet.rows.to_enum.map(&:values)
> 
> puts @header
> puts @dataSets

This is the output I get

> abc
> def
> ghi
> j&k

**Comment by davich** [comment]
Thanks for helping me debug this issue. I run exactly the same code on my machine and get the ampersand escaped.
creek-2.4.1 on OSX

```
$ cat xlsx.rb 
require 'creek'
@SanityWorkBook = Creek::Book.new "testfile.xlsx"
@sheet = @SanityWorkBook.sheets.detect {|sheet, index| sheet.name.eql? "Inspirations"}
@Header, *@datasets = @sheet.rows.to_enum.map(&:values)

puts @Header
puts @datasets

$ ruby xlsx.rb 
abc
def
ghi
j&amp;k
```

**Comment by davich** [comment]
I've created a PR with a couple of tests. One passes, the other fails: https://github.com/pythonicrubyist/creek/pull/75
It seems to be to do with the working one using shared strings (`j&k`) and the broken one using inlineStrings (`j&amp;k`)

**Comment by davich** [comment]
I fixed the issue with https://github.com/pythonicrubyist/creek/pull/76
Using 
```
node.read
node.value
```

instead of 
```
node.inner_xml
```

Can you please confirm this is the right approach? Thanks

**Comment by davich** [comment]
Hi @Rajagopalan-M , Just following up on this. How should we proceed? Thanks

**Comment by Rajagopalan-M** [comment]
I am able to read, I don't have any problem.

**Comment by davich** [comment]
Hi @Rajagopalan-M 
I have a PR with a failing test in https://github.com/pythonicrubyist/creek/pull/75 - This reproduces the issue.
Can you please look at it?
Thanks

**Comment by Rajagopalan-M** [comment]
Try RubyXl once whether it works for you, If it works, then leave away this
gem. For me, this gem works fine and fast as well.

**Comment by davich** [comment]
Can you merge #76  ?

**Comment by davich** [comment]
@pythonicrubyist ^^

**Comment by pythonicrubyist** [comment]
Merged. Thanks for your contribution.
