### ISSUE TITLE
NoMethodError: private method `open' called for Zip::File:Class

### ISSUE THREAD

**Issue by anujaware** [pythonicrubyist/creek#8]
Trying to use Creek::Book.new getting error
NoMethodError: private method `open' called for Zip::File:Class

**Comment by pythonicrubyist** [comment]
I am not able to reproduce this error. Perhaps the Excel file is not in the correct format.

**Comment by lsethi123** [comment]
@pythonicrubyist 

If you use rails 4+  then you need to add rubyzip gem in gemfile to resolve this error
