### ISSUE TITLE
Remove http dependency?

### ISSUE THREAD

**Issue by fanfilmu** [pythonicrubyist/creek#80]
Hello!

I would like to propose removing the `http` gem dependency entirely. From what I see, it's only used to download remote XLSX files, which, in my opinion, should be handled outside the gem by the devs (by their favourite http gem with 10 monkeypatches for their own super-secret security policy :) ).

Benefits that I see:
- does not require to download a lib which has tons of alternatives
- does not require users to update the lib to match Creek dependency
- prevents clashes with other gems depending on HTTP

Personally, it would allow me to update Creek without regenerating VCRs and solving problems that come with it... 😇

Let me know what you think!

**Comment by mdavidn** [comment]
Yes, please. The `http` gem brings six transitive dependencies, including one native extension.
