### ISSUE TITLE
How to get header as Key name?

### ISSUE THREAD

**Issue by leoplct** [pythonicrubyist/creek#82]
The first row of my excel has the header. How can I get the header name instead of "A", "B" etc.?

`{"A"=>"DATE, "B"=>"TEXT", "C"=>"TEXT", "D"=>"TEXT"}`

--> 

`{"Start date"=>"DATE, "First name"=>"TEXT", "Last name"=>"TEXT", "Address"=>"TEXT"}`

Would be great to parse header giving a regex expression. Just like Roo gem

**Comment by axlwild** [comment]
You can make a dictionary with the equivalence

equ = {"StartDate" => "A"}
and access with sheet[equ["StartDate"]]

**Comment by pythonicrubyist** [comment]
Good point. I have added it to the backlog.
