### ISSUE TITLE
Replace removed example xlsx file in README

### ISSUE THREAD

**Issue by lacostenycoder** [pythonicrubyist/creek#84]
Following the example in the README

This doesn't seem to work
Tested on MacOS, ruby version: ruby 2.6.2p47
creek version: creek (2.4.4).  It seems the example xlsx file doesn't exist.  This should probably be updated to pull from a more reliable source.  Why not just included an example xlsx file in this repo and use that?

```ruby
require 'creek'
remote_url = 'http://dev-builds.libreoffice.org/tmp/test.xlsx'
Creek::Book.new remote_url, remote: true
```

Raises 
```
...gems/ruby-2.4.1/gems/rubyzip-1.2.3/lib/zip/central_directory.rb:143:in `get_e_o_c_d': Zip end of central directory signature not found (Zip::Error)
```

**Comment by pythonicrubyist** [comment]
The remote URL parsing will be deprecated very soon.
