### ISSUE TITLE
Can't install Creek gem in Ruby 2.7

### ISSUE THREAD

**Issue by Rajagopalan-M** [pythonicrubyist/creek#90]
I can't install Creek gem in newest version of Ruby, it throws the following error

```
C:\>gem install creek
ERROR:  Error installing creek:
        The last version of nokogiri (>= 1.10.0) to support your Ruby & RubyGems was 1.10.7. Try installing it with `gem install nokogiri -v 1.10.7` and then running the current command again
        nokogiri requires Ruby version >= 2.3, < 2.7.dev. The current ruby version is 2.7.0.0.

```

**Comment by pythonicrubyist** [comment]
Creek is compatible with Ruby 2.7. You are probably missing some system requirement for nokogiri. You can troubleshoot by running gem install nokogiri -v 1.10.7

**Comment by Rajagopalan-M** [comment]
@pythonicrubyist 

it's saying `nokogiri requires Ruby version >= 2.3, < 2.7.dev. The current ruby version is 2.7.0.0` but your gem Runtime Dependencies (2): needs `nokogiri >= 1.10.0` , So it goes in a circle now. Your gem needs nokogiri but nokogiri can't be installed in ruby 2.7, so your gem can't be installed now.
